spring.application.name=repasoPC1
# docker run -p 5555:5432 -e POSTGRES_PASSWORD=123 -d postgres
#docker start mi_contenedor

spring.datasource.url=jdbc:postgresql://localhost:5555/postgres
spring.datasource.username=postgres
spring.datasource.password=123
#cada vez que corre, se borra y crea uno nuevo
spring.jpa.hibernate.ddl-auto=create-drop
#se van modificando los datos cada vez que se corre el programa
#spring.jpa.hibernate.ddl-auto=update




